/* eslint-disable no-console */
/**
 * One-shot scraper: generuje shared/src/bond-map-data.ts z katalogu obligacji
 * notowanych na Catalyst.
 *
 * Źródło: obligacje.pl — wyszukiwarka obligacji notowanych (lista ~900 serii:
 * emitent, kod, termin wykupu, rodzaj oprocentowania, kupon) + strony szczegółów
 * (/pl/obligacja/<KOD>: ISIN, wartość nominalna + waluta, status).
 *
 * Dlaczego nie gpwcatalyst.pl: WAF (F5) resetuje połączenia spoza przeglądarki
 * (curl/node fetch → ECONNRESET), a tabela notowań i tak nie zawiera nominału
 * ani daty wykupu. obligacje.pl serwuje statyczny HTML bez blokad.
 *
 * Używa wyłącznie publicznych stron HTML, z delayem 350 ms między requestami
 * (~6 min na pełny przebieg). Wygenerowany plik jest commitowany — runtime
 * nigdy nie uderza do obligacje.pl.
 *
 * Run:  npm run scrape:catalyst-bonds -w server
 */

import * as cheerio from 'cheerio';
import { writeFileSync } from 'fs';
import { resolve } from 'path';
import { BOND_MAP as EXISTING_BOND_MAP } from '../../shared/src/bond-map-data.js';

const LIST_URL = 'https://obligacje.pl/pl/narzedzia/wyszukiwarka-obligacji-notowanych';
const DETAIL_URL = (ticker: string) => `https://obligacje.pl/pl/obligacja/${ticker}`;
const DELAY_MS = 350;
const USER_AGENT =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122 Safari/537.36';

/** Prefiksy serii skarbowych/BGK — kopiowane z shared/src/bond-map.ts (TREASURY_BOND_RE). */
const TREASURY_RE = /^(OK|PS|DS|WS|WZ|IZ|TOS|FPC|IDS)\d{4}$/;

interface ListRow {
  emitent: string;
  ticker: string;
  maturityDate: string;
  couponType?: 'fixed' | 'floating' | 'zero';
  couponRate?: number;
}

interface BondEntry extends ListRow {
  isin: string;
  nominal: number;
  currency: string;
}

async function fetchHtml(url: string): Promise<string> {
  const resp = await fetch(url, { headers: { 'User-Agent': USER_AGENT } });
  if (!resp.ok) throw new Error(`HTTP ${resp.status} for ${url}`);
  return await resp.text();
}

function sleep(ms: number): Promise<void> {
  return new Promise((res) => setTimeout(res, ms));
}

function parseCouponType(rodzaj: string): 'fixed' | 'floating' | 'zero' | undefined {
  const lower = rodzaj.toLowerCase();
  if (lower.includes('stał')) return 'fixed';
  if (lower.includes('zmienn')) return 'floating';
  if (lower.includes('zerokupon') || lower.includes('dyskont')) return 'zero';
  return undefined;
}

function parseList(html: string): ListRow[] {
  const $ = cheerio.load(html);
  const rows: ListRow[] = [];
  $('table#tabela tbody tr').each((_, tr) => {
    const tds = $(tr).find('td');
    if (tds.length < 6) return;
    const emitent = $(tds[0]).text().trim();
    const ticker = $(tds[1]).text().trim().toUpperCase();
    const maturityDate = $(tds[2]).text().trim();
    const rodzaj = $(tds[3]).text().trim();
    const kuponTxt = $(tds[5]).text().trim();
    if (!ticker || !/^\d{4}-\d{2}-\d{2}$/.test(maturityDate)) return;
    const couponRate = kuponTxt.endsWith('%') ? parseFloat(kuponTxt) : undefined;
    rows.push({
      emitent,
      ticker,
      maturityDate,
      couponType: parseCouponType(rodzaj),
      couponRate: Number.isFinite(couponRate) ? couponRate : undefined,
    });
  });
  return rows;
}

/** Szczegóły: tabela <th>Etykieta:</th><td>wartość</td> — parsujemy regexem (struktura stabilna). */
function parseDetail(html: string): { isin: string; nominal: number; currency: string } | null {
  const isinMatch = html.match(/ISIN:<\/th>\s*<td>([A-Z0-9]+)<\/td>/);
  // "Wartość nominalna:</th> <td>1 000.00 PLN</td>" — spacje tysięcy, kropka dziesiętna
  const nominalMatch = html.match(/Wartość nominalna:<\/th>\s*<td>([\d\s .,]+)\s+([A-Z]{3})<\/td>/);
  if (!isinMatch || !nominalMatch) return null;
  const nominal = parseFloat(nominalMatch[1].replace(/[\s ]/g, '').replace(',', '.'));
  if (!Number.isFinite(nominal) || nominal <= 0) return null;
  return { isin: isinMatch[1], nominal, currency: nominalMatch[2] };
}

function segmentOf(row: ListRow): 'treasury' | 'corporate' {
  if (TREASURY_RE.test(row.ticker)) return 'treasury';
  if (row.emitent.toLowerCase().includes('skarb państwa')) return 'treasury';
  return 'corporate';
}

function generateFile(entries: BondEntry[]): string {
  const sorted = [...entries].sort((a, b) => a.ticker.localeCompare(b.ticker));
  const lines: string[] = [];
  const today = new Date().toISOString().slice(0, 10);
  lines.push(
    `// GENERATED by server/scripts/scrape-catalyst-bonds.ts on ${today} — do not edit by hand.`,
  );
  lines.push(
    '// Źródło: https://obligacje.pl/pl/narzedzia/wyszukiwarka-obligacji-notowanych (+ strony szczegółów).',
  );
  lines.push('');
  lines.push('export interface BondMapEntry {');
  lines.push('  isin: string;');
  lines.push('  ticker: string;');
  lines.push('  /** Nazwa emitenta (np. "Skarb Państwa", "KGHM Polska Miedź S.A."). */');
  lines.push('  name: string;');
  lines.push('  /** Wartość nominalna 1 obligacji w walucie `currency`. */');
  lines.push('  nominal: number;');
  lines.push('  currency: string;');
  lines.push('  /** Data wykupu YYYY-MM-DD. */');
  lines.push('  maturityDate: string;');
  lines.push(
    '  /** treasury = skarbowe + gwarantowane przez SP (BGK FPC/IDS); corporate = pozostałe. */',
  );
  lines.push("  segment: 'treasury' | 'corporate';");
  lines.push("  couponType?: 'fixed' | 'floating' | 'zero';");
  lines.push('  /** Oprocentowanie w bieżącym okresie odsetkowym (%). */');
  lines.push('  couponRate?: number;');
  lines.push('}');
  lines.push('');
  lines.push('/** Klucz: ticker Catalyst uppercase (np. "DS1030", "FPC0733", "KGH0629"). */');
  lines.push('export const BOND_MAP: Record<string, BondMapEntry> = {');
  for (const e of sorted) {
    const fields = [
      `isin: '${e.isin}'`,
      `ticker: '${e.ticker}'`,
      `name: ${JSON.stringify(e.emitent)}`,
      `nominal: ${e.nominal}`,
      `currency: '${e.currency}'`,
      `maturityDate: '${e.maturityDate}'`,
      `segment: '${segmentOf(e)}'`,
    ];
    if (e.couponType) fields.push(`couponType: '${e.couponType}'`);
    if (e.couponRate !== undefined) fields.push(`couponRate: ${e.couponRate}`);
    // Klucz cytowany gdy nie jest poprawnym identyfikatorem JS (np. "BOS0735-K")
    const key = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(e.ticker) ? e.ticker : JSON.stringify(e.ticker);
    lines.push(`  ${key}: { ${fields.join(', ')} },`);
  }
  lines.push('};');
  lines.push('');
  return lines.join('\n');
}

async function main(): Promise<void> {
  console.log(`Pobieram listę: ${LIST_URL}`);
  const listHtml = await fetchHtml(LIST_URL);
  const rows = parseList(listHtml);
  console.log(`Znaleziono ${rows.length} obligacji w wyszukiwarce.`);
  if (rows.length === 0) throw new Error('Pusta lista — zmieniła się struktura strony?');

  const entries: BondEntry[] = [];
  const failed: string[] = [];
  for (let i = 0; i < rows.length; i++) {
    const row = rows[i];
    await sleep(DELAY_MS);
    try {
      let html: string;
      try {
        html = await fetchHtml(DETAIL_URL(row.ticker));
      } catch {
        await sleep(DELAY_MS * 4); // jedna ponowna próba po dłuższej pauzie
        html = await fetchHtml(DETAIL_URL(row.ticker));
      }
      const detail = parseDetail(html);
      if (!detail) {
        failed.push(row.ticker);
        continue;
      }
      entries.push({ ...row, ...detail });
    } catch {
      failed.push(row.ticker);
    }
    if ((i + 1) % 50 === 0) console.log(`  ${i + 1}/${rows.length}…`);
  }

  console.log(`Sparsowano ${entries.length}/${rows.length}; błędy: ${failed.length}`);
  if (failed.length > 0) console.log(`  Pominięte: ${failed.join(', ')}`);
  if (entries.length < rows.length * 0.9) {
    throw new Error('Ponad 10% braków — nie nadpisuję mapy, sprawdź strukturę strony.');
  }

  // MERGE z istniejącą mapą: wyszukiwarka obligacje.pl listuje tylko NOTOWANE serie,
  // więc obligacja po wykupie znika z listy — a stare eksporty Bossy nadal zawierają
  // jej transakcje i potrzebują klasyfikacji (ISIN/nominał/zapadalność się nie zmieniają).
  // Świeży scrape wygrywa dla wspólnych tickerów (aktualny kupon), wpisy historyczne
  // zostają. Przykład: PND0618 (Polnord, wykup 2018) nie wróci z listy notowanych.
  const scrapedTickers = new Set(entries.map((e) => e.ticker));
  let preserved = 0;
  for (const old of Object.values(EXISTING_BOND_MAP)) {
    if (scrapedTickers.has(old.ticker)) continue;
    entries.push({
      emitent: old.name,
      ticker: old.ticker,
      maturityDate: old.maturityDate,
      couponType: old.couponType,
      couponRate: old.couponRate,
      isin: old.isin,
      nominal: old.nominal,
      currency: old.currency,
    });
    preserved++;
  }
  if (preserved > 0) console.log(`Zachowano ${preserved} wpisów historycznych (już nienotowane).`);

  const outPath = resolve(process.cwd(), '../shared/src/bond-map-data.ts');
  writeFileSync(outPath, generateFile(entries), 'utf-8');
  console.log(`Zapisano ${entries.length} obligacji → ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
