/**
 * Static NewConnect ticker map — offline fallback for ISIN resolver.
 *
 * When Stooq API is rate-limited, the resolver uses this map to correctly
 * identify NC stocks instead of falling through to Yahoo (which maps them
 * to wrong foreign tickers like MINERAL → NAK).
 *
 * Source: money.pl NC listing + manual ticker mapping.
 * Format: { ticker: Stooq symbol (uppercase), name: Bossa-style short name (uppercase) }
 */

export const NC_TICKER_MAP = [
  { ticker: '4MB', name: '4MOBILITY' },
  { ticker: '7FT', name: '7FIT' },
  { ticker: '7LV', name: '7LEVELS' },
  { ticker: 'AAS', name: 'AALLIANCE' },
  { ticker: 'ABK', name: 'ABAK' },
  { ticker: 'ADX', name: 'ADATEX' },
  { ticker: 'AER', name: 'AERFINANC' },
  { ticker: 'AFC', name: 'AKCEPTFIN' },
  { ticker: 'AFH', name: 'AFHOL' },
  { ticker: 'AGL', name: 'AGROLIGA' },
  { ticker: 'AGP', name: 'AGROMEP' },
  { ticker: 'AIN', name: 'ABSINVEST' },
  { ticker: 'AIT', name: 'AITON' },
  { ticker: 'AME', name: 'AMESA' },
  { ticker: 'AOL', name: 'ANALIZY' },
  { ticker: 'APA', name: 'APANET' },
  { ticker: 'APC', name: 'APOLLO' },
  { ticker: 'APS', name: 'APS' },
  { ticker: 'AQA', name: 'AQUAPOZ' },
  { ticker: 'AQT', name: 'AQUATECH' },
  { ticker: 'AQU', name: 'AQUABB' },
  { ticker: 'ARG', name: 'ARTGAMES' },
  { ticker: 'ARI', name: 'ARI' },
  { ticker: 'ASA', name: 'APIS' },
  { ticker: 'ASR', name: 'ASTRO' },
  { ticker: 'ATA', name: 'ATCCARGO' },
  { ticker: 'ATJ', name: 'ATOMJELLY' },
  { ticker: 'ATO', name: 'ATONHT' },
  { ticker: 'AUX', name: 'AUXILIA' },
  { ticker: 'AVE', name: 'ADVERTIGO' },
  { ticker: 'AZC', name: 'AZTEC' },
  { ticker: 'BAC', name: 'BACT' },
  { ticker: 'BEE', name: 'BEEIN' },
  { ticker: 'BEP', name: 'BIOMASS' },
  { ticker: 'BER', name: 'BIOERG' },
  { ticker: 'BGD', name: 'BIOGENED' },
  { ticker: 'BHX', name: 'BINARY' },
  { ticker: 'BIG', name: 'BASEIG' },
  { ticker: 'BKD', name: 'BKDGAMES' },
  { ticker: 'BLF', name: 'BELEAF' },
  { ticker: 'BLT', name: 'BALTICON' },
  { ticker: 'BPC', name: 'BPC' },
  { ticker: 'BPN', name: 'BLACKPOIN' },
  { ticker: 'BRH', name: 'BERGHOLDI' },
  { ticker: 'BRO', name: 'CZARNKOW' },
  { ticker: 'BRP', name: 'BLACKROSE' },
  { ticker: 'BSA', name: 'BRAS' },
  { ticker: 'BSH', name: 'BSH' },
  { ticker: 'BSN', name: 'BRAINSCAN' },
  { ticker: 'BTC', name: 'BTCSTUDIO' },
  { ticker: 'BTF', name: 'BTCS' },
  { ticker: 'BTK', name: 'BIZTECH' },
  { ticker: 'CAI', name: 'CARLSON' },
  { ticker: 'CBD', name: 'CANNABIS' },
  { ticker: 'CCR', name: 'CONSTANCE' },
  { ticker: 'CCS', name: 'CCS' },
  { ticker: 'CDA', name: 'CDA' },
  { ticker: 'CFG', name: 'CFG' },
  { ticker: 'CFS', name: 'CFSA' },
  { ticker: 'CHP', name: 'CHERRY' },
  { ticker: 'CLA', name: 'CONSOLE' },
  { ticker: 'CMC', name: 'COMECO' },
  { ticker: 'CMI', name: 'CMI' },
  { ticker: 'COR', name: 'COREY' },
  { ticker: 'COS', name: 'COSMA' },
  { ticker: 'CRB', name: 'CARBONSTU' },
  { ticker: 'CRC', name: 'CARPATHIA' },
  { ticker: 'CRP', name: 'CEREALPLT' },
  { ticker: 'CST', name: 'CSTORE' },
  { ticker: 'CTE', name: 'CTEGROUP' },
  { ticker: 'CTF', name: 'CENTURION' },
  { ticker: 'CWA', name: 'CONSOLEW' },
  { ticker: 'DDI', name: 'DDISTANCE' },
  { ticker: 'DEG', name: 'DETGAMES' },
  { ticker: 'DFH', name: 'DEFENCEH' },
  { ticker: 'DGN', name: 'DGNET' },
  { ticker: 'DGS', name: 'DEMGAMES' },
  { ticker: 'DIV', name: 'DIVOLIO' },
  { ticker: 'DKR', name: 'DEKTRA' },
  { ticker: 'DNS', name: 'DANKS' },
  { ticker: 'DPG', name: 'DARKPOINT' },
  { ticker: 'DRF', name: 'DRFINANCE' },
  { ticker: 'DRG', name: 'DRAGEUS' },
  { ticker: 'DTX', name: 'DITIX' },
  { ticker: 'DUA', name: 'DUALITY' },
  { ticker: 'EBX', name: 'EKOBOX' },
  { ticker: 'ECC', name: 'ECCGAMES' },
  { ticker: 'ECK', name: 'EUROSNACK' },
  { ticker: 'ECL', name: 'ECL' },
  { ticker: 'ECN', name: 'ECNOLOGY' },
  { ticker: 'ECT', name: 'ECO5TECH' },
  { ticker: 'EDL', name: 'EDITELPL' },
  { ticker: 'EEE', name: 'EKIPA' },
  { ticker: 'EFE', name: 'EFENERGII' },
  { ticker: 'EGH', name: 'EKOPOL' },
  { ticker: 'EGY', name: 'ENERGY' },
  { ticker: 'EKE', name: 'EKOOZE' },
  { ticker: 'EKS', name: 'EKIOSK' },
  { ticker: 'ELM', name: 'EMONT' },
  { ticker: 'ELQ', name: 'ELQ' },
  { ticker: 'EMP', name: 'EMPLOCITY' },
  { ticker: 'END', name: 'ENEIDA' },
  { ticker: 'EPR', name: 'EKOPARK' },
  { ticker: 'ERA', name: 'ERATONRG' },
  { ticker: 'ESG', name: 'ESHOPPING' },
  { ticker: 'ESK', name: 'ESKIMOS' },
  { ticker: 'ETX', name: 'EUROTAX' },
  { ticker: 'EUV', name: 'EUVIC' },
  { ticker: 'EXA', name: 'EXAMOBILE' },
  { ticker: 'EXC', name: 'EXCELLENC' },
  { ticker: 'EXM', name: 'EXIMIT' },
  { ticker: 'F51', name: 'FARM51' },
  { ticker: 'FAR', name: 'FARMINN' },
  { ticker: 'FEM', name: 'FEMTECH' },
  { ticker: 'FFP', name: 'FARMYFO' },
  { ticker: 'FHD', name: 'FHDOM' },
  { ticker: 'FIG', name: 'FIGENE' },
  { ticker: 'FKD', name: 'FABRYKAKD' },
  { ticker: 'FLG', name: 'FALCON' },
  { ticker: 'FOR', name: 'FOREVEREN' },
  { ticker: 'FOX', name: 'SPACEFOX' },
  { ticker: 'FPO', name: 'FORPOSTA' },
  { ticker: 'FRB', name: 'FORBUILD' },
  { ticker: 'FRM', name: 'FREEMIND' },
  { ticker: 'FRW', name: 'FROZENWAY' },
  { ticker: 'FTH', name: 'FINTECH' },
  { ticker: 'FTL', name: 'FOOTHILLS' },
  { ticker: 'FVE', name: 'FOTOVOLT' },
  { ticker: 'GAL', name: 'GALVO' },
  { ticker: 'GAR', name: 'GARIN' },
  { ticker: 'GDC', name: 'GAMEDUST' },
  { ticker: 'GDS', name: 'GDEVS' },
  { ticker: 'GEN', name: 'GENOMED' },
  { ticker: 'GHT', name: 'GAMEHUNT' },
  { ticker: 'GHY', name: 'GHYDROGEN' },
  { ticker: 'GKS', name: 'GKSKAT' },
  { ticker: 'GMB', name: 'GAMESBOX' },
  { ticker: 'GME', name: 'GRMEDIA' },
  { ticker: 'GMV', name: 'GAMIVO' },
  { ticker: 'GMZ', name: 'GRUPAMZ' },
  { ticker: 'GNG', name: 'GENRG' },
  { ticker: 'GNS', name: 'NIEWIADOW' },
  { ticker: 'GOL', name: 'GOLAB' },
  { ticker: 'GOV', name: 'GOVENA' },
  { ticker: 'GRC', name: 'GRUPAREC' },
  { ticker: 'GRE', name: 'GREENENER' },
  { ticker: 'GRL', name: 'GREENLANE' },
  { ticker: 'GRM', name: 'GREMPCO' },
  { ticker: 'GRZ', name: 'GREENZEB' },
  { ticker: 'GTF', name: 'GOTFI' },
  { ticker: 'GTS', name: 'GEOTRANS' },
  { ticker: 'GX1', name: 'GENXONE' },
  { ticker: 'HEN', name: 'HYENERGY' },
  { ticker: 'HER', name: 'HILANDER' },
  { ticker: 'HMP', name: 'HEMP' },
  { ticker: 'HOR', name: 'HORTICO' },
  { ticker: 'HPE', name: 'HIPOWERSA' },
  { ticker: 'HPG', name: 'HONEYPAY' },
  { ticker: 'HPM', name: 'HIPROMINE' },
  { ticker: 'HPS', name: 'HYDRAPRES' },
  { ticker: 'HRC', name: 'GRUPAHRC' },
  { ticker: 'HRL', name: 'HORNIGOLD' },
  { ticker: 'HRT', name: 'HURTIMEX' },
  { ticker: 'HUB', name: 'HUBTECH' },
  { ticker: 'IBC', name: 'IBCPOLSKA' },
  { ticker: 'ICD', name: 'ICPD' },
  { ticker: 'ICG', name: 'ICECODE' },
  { ticker: 'IDH', name: 'IDH' },
  { ticker: 'IFA', name: 'INFRA' },
  { ticker: 'IGT', name: 'IGORIA' },
  { ticker: 'IMG', name: 'IMMGAMES' },
  { ticker: 'IMR', name: 'INTM' },
  { ticker: 'INM', name: 'INVENTION' },
  { ticker: 'INS', name: 'INDOS' },
  { ticker: 'INT', name: 'INTERNITY' },
  { ticker: 'IPW', name: 'IMAGEPWR' },
  { ticker: 'ISD', name: 'INSIDPARK' },
  { ticker: 'IUS', name: 'IU' },
  { ticker: 'IVE', name: 'INVESTEKO' },
  { ticker: 'IVO', name: 'INCUVO' },
  { ticker: 'IWS', name: 'IRONWOLF' },
  { ticker: 'JJB', name: 'JUJUBEE' },
  { ticker: 'JRC', name: 'JRCGROUP' },
  { ticker: 'K2P', name: 'KOOL2PLAY' },
  { ticker: 'KBJ', name: 'KBJ' },
  { ticker: 'KBT', name: 'KLABATER' },
  { ticker: 'KLE', name: 'KLEPSYDRA' },
  { ticker: 'KLK', name: 'KOLEJKOWO' },
  { ticker: 'KLN', name: 'KLON' },
  { ticker: 'KME', name: 'KME' },
  { ticker: 'KOR', name: 'KORBANK' },
  { ticker: 'KPC', name: 'KUPIEC' },
  { ticker: 'KPI', name: 'KANCELWEC' },
  { ticker: 'KUB', name: 'KUBOTA' },
  { ticker: 'LBD', name: 'LOKATYBUD' },
  { ticker: 'LCN', name: 'LABOCANNA' },
  { ticker: 'LEG', name: 'LEGIMI' },
  { ticker: 'LET', name: 'LETUS' },
  { ticker: 'LGT', name: 'LGTRADE' },
  { ticker: 'LHD', name: 'LICHTHUND' },
  { ticker: 'LMG', name: 'LMGAMES' },
  { ticker: 'LTM', name: 'LTGAMES' },
  { ticker: 'LUD', name: 'LUDUS' },
  { ticker: 'LUG', name: 'LUG' },
  { ticker: 'LUK', name: 'LUKARDI' },
  { ticker: 'LUO', name: 'LUON' },
  { ticker: 'LXB', name: 'LEXBONO' },
  { ticker: 'M4B', name: 'M4B' },
  { ticker: 'MAD', name: 'MADKOM' },
  { ticker: 'MAZ', name: 'MAZOP' },
  { ticker: 'MBF', name: 'MBFGROUP' },
  { ticker: 'MCD', name: 'MYCODERN' },
  { ticker: 'MDA', name: 'MEDAPP' },
  { ticker: 'MDB', name: 'MEDICOBIO' },
  { ticker: 'MDP', name: 'MEDCAMP' },
  { ticker: 'MDT', name: 'MEDTECH' },
  { ticker: 'MER', name: 'MERA' },
  { ticker: 'MFD', name: 'MFOOD' },
  { ticker: 'MGS', name: 'MADNETIC' },
  { ticker: 'MIG', name: 'MILITARY' },
  { ticker: 'MLB', name: 'MAKOLAB' },
  { ticker: 'MLM', name: 'MILISYS' },
  { ticker: 'MLP', name: 'MILKPOL' },
  { ticker: 'MLT', name: 'MOONLIT' },
  { ticker: 'MMC', name: 'MMCPL' },
  { ticker: 'MMS', name: 'MADMIND' },
  { ticker: 'MND', name: 'MINERAL' },
  { ticker: 'MNS', name: 'MENNICASK' },
  { ticker: 'MO2', name: 'MOLIERA2' },
  { ticker: 'MPS', name: 'MEGAPIXEL' },
  { ticker: 'MPY', name: 'MPAY' },
  { ticker: 'MRD', name: 'MEDARD' },
  { ticker: 'MRG', name: 'MERLINGRP' },
  { ticker: 'MRH', name: 'HAMBURGER' },
  { ticker: 'MRK', name: 'MARKA' },
  { ticker: 'MSM', name: 'MSM' },
  { ticker: 'MTE', name: 'MTENERGIA' },
  { ticker: 'MTN', name: 'MILTON' },
  { ticker: 'MUN', name: 'MUNAR' },
  { ticker: 'MVR', name: 'MOVGAMVR' },
  { ticker: 'MXP', name: 'MAXIPIZZA' },
  { ticker: 'NFP', name: 'NFPL' },
  { ticker: 'NGD', name: 'NOGRVDEV' },
  { ticker: 'NOB', name: 'NOOBZ' },
  { ticker: 'NOV', name: 'NOVINA' },
  { ticker: 'NRS', name: 'NEURONE' },
  { ticker: 'NST', name: 'NESTMEDIC' },
  { ticker: 'NTS', name: 'NOTORIA' },
  { ticker: 'NTV', name: 'NTVSA' },
  { ticker: 'NWA', name: 'NWAI' },
  { ticker: 'NXB', name: 'NEXTBIKE' },
  { ticker: 'O2T', name: 'ONE2TRIBE' },
  { ticker: 'OLY', name: 'OLYMP' },
  { ticker: 'ONC', name: 'ONICO' },
  { ticker: 'ONE', name: '1SOLUTION' },
  { ticker: 'OPI', name: 'OPTIGIS' },
  { ticker: 'ORG', name: 'ORGANIC' },
  { ticker: 'ORL', name: 'ORZLOPONY' },
  { ticker: 'OUT', name: 'OUTDOORZY' },
  { ticker: 'OVI', name: 'OVIDWORKS' },
  { ticker: 'OXY', name: 'OXYGEN' },
  { ticker: 'OZE', name: 'OZECAPITAL' },
  { ticker: 'P24', name: 'PRESENT24' },
  { ticker: 'P2B', name: 'PLANETB2B' },
  { ticker: 'P2C', name: 'P2CHILL' },
  { ticker: 'PAC', name: 'PROACTA' },
  { ticker: 'PBB', name: 'PREFABET' },
  { ticker: 'PBT', name: 'PBGAMES' },
  { ticker: 'PDG', name: 'PYRAMID' },
  { ticker: 'PFG', name: 'PREFAGRP' },
  { ticker: 'PGG', name: 'PROGUNSGR' },
  { ticker: 'PIT', name: 'POLARISIT' },
  { ticker: 'PIX', name: 'PIXELCROW' },
  { ticker: 'PLG', name: 'PLGROUP' },
  { ticker: 'PLI', name: 'PLATIGE' },
  { ticker: 'PLM', name: 'POLMAN' },
  { ticker: 'PLT', name: 'PLOTTWIST' },
  { ticker: 'PMG', name: 'PGMSA' },
  { ticker: 'PNT', name: 'POINTPACK' },
  { ticker: 'PNW', name: 'PLANTWEAR' },
  { ticker: 'PPG', name: 'PUNCHPUNK' },
  { ticker: 'PRA', name: 'PRIME' },
  { ticker: 'PRE', name: 'PRESIDENT' },
  { ticker: 'PRH', name: 'POLHOLROZ' },
  { ticker: 'PRN', name: 'PARTNER' },
  { ticker: 'PRO', name: 'PROMISE' },
  { ticker: 'PRS', name: 'PRYMUS' },
  { ticker: 'PSH', name: 'POLYSLASH' },
  { ticker: 'PSM', name: 'PLASMA' },
  { ticker: 'PTE', name: 'PARCELTEC' },
  { ticker: 'PTN', name: 'POLTRONIC' },
  { ticker: 'QON', name: 'QUARTICON' },
  { ticker: 'QRT', name: 'QUART' },
  { ticker: 'QUB', name: 'QUBICGMS' },
  { ticker: 'RAY', name: 'PURPLERAY' },
  { ticker: 'RBS', name: 'ROBINSON' },
  { ticker: 'RCA', name: 'ROCCA' },
  { ticker: 'RCM', name: 'REDCARPET' },
  { ticker: 'RCW', name: 'RUCHCHORZ' },
  { ticker: 'RDG', name: 'READGENE' },
  { ticker: 'RGL', name: 'ROBSGROUP' },
  { ticker: 'RNT', name: 'PRIVRNT' },
  { ticker: 'RRH', name: 'RRHGROUP' },
  { ticker: 'RSG', name: 'RSGAMES' },
  { ticker: 'RSP', name: 'REMORSOL' },
  { ticker: 'RST', name: 'ROAD' },
  { ticker: 'S4E', name: 'S4E' },
  { ticker: 'SBE', name: 'SOFTBLUE' },
  { ticker: 'SCS', name: 'STEMCELLS' },
  { ticker: 'SDG', name: 'SUNDRAGON' },
  { ticker: 'SDS', name: 'SDSOPTIC' },
  { ticker: 'SED', name: 'SEDIVIO' },
  { ticker: 'SEV', name: 'SEVENET' },
  { ticker: 'SFD', name: 'SFD' },
  { ticker: 'SFK', name: 'SFKPOLKAP' },
  { ticker: 'SHY', name: 'SHEEPYARD' },
  { ticker: 'SIN', name: 'SOLARINOV' },
  { ticker: 'SKN', name: 'SAKANA' },
  { ticker: 'SKY', name: 'STOHID' },
  { ticker: 'SLT', name: 'SAULETECH' },
  { ticker: 'SMT', name: 'SIMTERACT' },
  { ticker: 'SNG', name: 'SYNERGA' },
  { ticker: 'SNN', name: 'SUNNET' },
  { ticker: 'SOK', name: 'SONKA' },
  { ticker: 'STA', name: 'STARWARD' },
  { ticker: 'STD', name: 'STANDREW' },
  { ticker: 'STI', name: 'STILO' },
  { ticker: 'SUN', name: 'SUNTECH' },
  { ticker: 'SWM', name: 'SWMANSION' },
  { ticker: 'SYG', name: 'SYGNIS' },
  { ticker: 'SZR', name: 'SZAR' },
  { ticker: 'T2P', name: 'TERMO2PWR' },
  { ticker: 'TCR', name: 'TECHROBOT' },
  { ticker: 'TEC', name: 'TECNTICA' },
  { ticker: 'TGG', name: 'TRIGGO' },
  { ticker: 'TGS', name: 'TRUEGS' },
  { ticker: 'THD', name: 'THEDUST' },
  { ticker: 'TLG', name: 'TELGAM' },
  { ticker: 'TLO', name: 'TELESTO' },
  { ticker: 'TLS', name: 'TELESTR' },
  { ticker: 'TME', name: 'TERMOEXP' },
  { ticker: 'TMP', name: 'TELEMEDPL' },
  { ticker: 'TNT', name: 'TNTPROENR' },
  { ticker: 'TOS', name: 'TAMEX' },
  { ticker: 'TRX', name: 'TREX' },
  { ticker: 'TXN', name: 'TAXNET' },
  { ticker: 'UFC', name: 'UNIFIED' },
  { ticker: 'UFG', name: 'UFGAMES' },
  { ticker: 'UNL', name: 'UNILABGAM' },
  { ticker: 'UNV', name: 'UNIVERSE' },
  { ticker: 'VAI', name: 'VOLARIA' },
  { ticker: 'VAR', name: 'VARSAV' },
  { ticker: 'VDS', name: 'VIDIS' },
  { ticker: 'VEE', name: 'VEE' },
  { ticker: 'VER', name: 'MPLVERBUM' },
  { ticker: 'VFA', name: 'VRFABRIC' },
  { ticker: 'VIV', name: 'VISION' },
  { ticker: 'VKT', name: 'VAKOMTEK' },
  { ticker: 'VLT', name: 'VOOLT' },
  { ticker: 'VMX', name: 'VMAXSA' },
  { ticker: 'VRB', name: 'VERBICOM' },
  { ticker: 'VRF', name: 'VRFACTORY' },
  { ticker: 'WGP', name: 'WGPARTNER' },
  { ticker: 'WHH', name: 'WERTHHOLZ' },
  { ticker: 'WLI', name: 'WILDINT' },
  { ticker: 'WOD', name: 'WODKAN' },
  { ticker: 'WRE', name: 'WESTREAL' },
  { ticker: 'WRL', name: 'WIERZYCL' },
  { ticker: 'XBS', name: 'XBSPROLOG' },
  { ticker: 'XDD', name: 'MENTZEN' },
  { ticker: 'YBS', name: 'YELLOWBOS' },
  { ticker: 'YOS', name: 'YOSHI' },
  { ticker: 'YTF', name: 'YETIFORCE' },
  { ticker: 'ZEN', name: 'ZENERIS' },
  { ticker: 'ZRX', name: 'ZORTRAX' },
] as const;

// Pre-built lookup maps for O(1) access
type NcEntry = { ticker: string; name: string };
const byTicker = new Map<string, NcEntry>(NC_TICKER_MAP.map(e => [e.ticker, e]));
const byName = new Map<string, NcEntry>(NC_TICKER_MAP.map(e => [e.name, e]));

/**
 * Find NC ticker by Bossa paper name (e.g., "MINERAL" from "MINERAL-NC").
 *
 * Matching strategies:
 * 1. Exact match on Stooq ticker (e.g., "MND" → MND)
 * 2. Exact match on Bossa-style name (e.g., "MINERAL" → MND)
 * 3. Prefix match on name (e.g., "MINERAL" matches "MINERALM..." if it existed)
 */
export function findNcTicker(
  bossaName: string,
): { ticker: string; name: string } | null {
  const upper = bossaName.toUpperCase();

  // 1. Exact ticker match (Bossa sometimes uses the ticker directly)
  const tickerHit = byTicker.get(upper);
  if (tickerHit) return { ticker: tickerHit.ticker, name: tickerHit.name };

  // 2. Exact name match (most common: MINERAL → MND)
  const nameHit = byName.get(upper);
  if (nameHit) return { ticker: nameHit.ticker, name: nameHit.name };

  // 3. Prefix match — Bossa name is prefix of map name or vice versa
  //    e.g., "PRESIDENT" matches "PRESIDENT" (exact), "MINERAL" matches "MINERAL"
  for (const entry of NC_TICKER_MAP) {
    if (entry.name.startsWith(upper) || upper.startsWith(entry.name)) {
      return { ticker: entry.ticker, name: entry.name };
    }
  }

  return null;
}
